name: Standard Node.js CI
on:
  push:
    branches: [$default-branch]
  pull_request:
    branches: [$default-branch]

jobs:
  ci:
    uses: eldong/.github/.github/workflows/demo3-reusable-ci.yml@main
    with:
      node-version: "20"
